// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokMultilink, StoryblokAsset, StoryblokRichtext } from '../storyblok.d.ts';
export interface Button {
  text: string;
  link: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  style?: "" | "gray" | "black";
  component: "button";
  _uid: string;
  [k: string]: unknown;
}

export interface Contact {
  title: string;
  subtitle: string;
  address: string;
  phone: string;
  email: string;
  component: "Contact";
  _uid: string;
  [k: string]: unknown;
}

export interface CountDown {
  background_image?: StoryblokAsset;
  title: string;
  description: string;
  date: string;
  features: (
    | Button
    | Contact
    | CountDown
    | CountdownFeature
    | FaqItem
    | FaqSection
    | FeaturedCars
    | FeatureItem
    | Features
    | Footer
    | GridCard
    | Hero
    | HeroVideo
    | ImageGrid
    | ImageText
    | Navbar
    | NavItem
    | Page
    | Process
    | ProcessItem
    | SiteConfig
    | SocialLinkItem
  )[];
  component: "CountDown";
  _uid: string;
  [k: string]: unknown;
}

export interface CountdownFeature {
  title: string;
  description: string;
  component: "countdown_feature";
  _uid: string;
  [k: string]: unknown;
}

export interface FaqItem {
  question: string;
  answer: string;
  component: "faq_item";
  _uid: string;
  [k: string]: unknown;
}

export interface FaqSection {
  header?: string;
  title: string;
  image?: StoryblokAsset;
  faqs: FaqItem[];
  button?: Button[];
  component: "FaqSection";
  _uid: string;
  [k: string]: unknown;
}

export interface FeaturedCars {
  title: string;
  header?: string;
  description: string;
  center_content: boolean;
  featured_only?: boolean;
  featured_cars_button?: (
    | Button
    | Contact
    | CountDown
    | CountdownFeature
    | FaqItem
    | FaqSection
    | FeaturedCars
    | FeatureItem
    | Features
    | Footer
    | GridCard
    | Hero
    | HeroVideo
    | ImageGrid
    | ImageText
    | Navbar
    | NavItem
    | Page
    | Process
    | ProcessItem
    | SiteConfig
    | SocialLinkItem
  )[];
  component: "Featured Cars";
  _uid: string;
  [k: string]: unknown;
}

export interface FeatureItem {
  title: string;
  description: string;
  component: "feature_item";
  _uid: string;
  [k: string]: unknown;
}

export interface Features {
  background_image?: StoryblokAsset;
  title: string;
  features: FeatureItem[];
  features_button?: Button[];
  component: "Features";
  _uid: string;
  [k: string]: unknown;
}

export interface Footer {
  footer_logo?: StoryblokAsset;
  logo?: StoryblokAsset;
  tagline?: string;
  social_links?: (
    | Button
    | Contact
    | CountDown
    | CountdownFeature
    | FaqItem
    | FaqSection
    | FeaturedCars
    | FeatureItem
    | Features
    | Footer
    | GridCard
    | Hero
    | HeroVideo
    | ImageGrid
    | ImageText
    | Navbar
    | NavItem
    | Page
    | Process
    | ProcessItem
    | SiteConfig
    | SocialLinkItem
  )[];
  link_columns?: (
    | Button
    | Contact
    | CountDown
    | CountdownFeature
    | FaqItem
    | FaqSection
    | FeaturedCars
    | FeatureItem
    | Features
    | Footer
    | GridCard
    | Hero
    | HeroVideo
    | ImageGrid
    | ImageText
    | Navbar
    | NavItem
    | Page
    | Process
    | ProcessItem
    | SiteConfig
    | SocialLinkItem
  )[];
  column_1_headline?: string;
  column_2_headline?: string;
  column_3_headline?: string;
  column_4_headline?: string;
  column_1_links?: (
    | Button
    | Contact
    | CountDown
    | CountdownFeature
    | FaqItem
    | FaqSection
    | FeaturedCars
    | FeatureItem
    | Features
    | Footer
    | GridCard
    | Hero
    | HeroVideo
    | ImageGrid
    | ImageText
    | Navbar
    | NavItem
    | Page
    | Process
    | ProcessItem
    | SiteConfig
    | SocialLinkItem
  )[];
  column_2_links?: (
    | Button
    | Contact
    | CountDown
    | CountdownFeature
    | FaqItem
    | FaqSection
    | FeaturedCars
    | FeatureItem
    | Features
    | Footer
    | GridCard
    | Hero
    | HeroVideo
    | ImageGrid
    | ImageText
    | Navbar
    | NavItem
    | Page
    | Process
    | ProcessItem
    | SiteConfig
    | SocialLinkItem
  )[];
  column_3_links?: (
    | Button
    | Contact
    | CountDown
    | CountdownFeature
    | FaqItem
    | FaqSection
    | FeaturedCars
    | FeatureItem
    | Features
    | Footer
    | GridCard
    | Hero
    | HeroVideo
    | ImageGrid
    | ImageText
    | Navbar
    | NavItem
    | Page
    | Process
    | ProcessItem
    | SiteConfig
    | SocialLinkItem
  )[];
  column_4_links?: (
    | Button
    | Contact
    | CountDown
    | CountdownFeature
    | FaqItem
    | FaqSection
    | FeaturedCars
    | FeatureItem
    | Features
    | Footer
    | GridCard
    | Hero
    | HeroVideo
    | ImageGrid
    | ImageText
    | Navbar
    | NavItem
    | Page
    | Process
    | ProcessItem
    | SiteConfig
    | SocialLinkItem
  )[];
  contact_info?: StoryblokRichtext;
  email?: unknown;
  phone?: string;
  footer_cta_headline?: string;
  footer_cta_text?: string;
  footer_cta_button?: (
    | Button
    | Contact
    | CountDown
    | CountdownFeature
    | FaqItem
    | FaqSection
    | FeaturedCars
    | FeatureItem
    | Features
    | Footer
    | GridCard
    | Hero
    | HeroVideo
    | ImageGrid
    | ImageText
    | Navbar
    | NavItem
    | Page
    | Process
    | ProcessItem
    | SiteConfig
    | SocialLinkItem
  )[];
  footer_background_color?: string;
  footer_text_color?: string;
  footer_link_color?: string;
  footer_border_color?: string;
  show_footer_border?: boolean;
  footer_spacing?: string;
  copyright?: string;
  footer_layout?: string;
  footer_width?: string;
  component: "footer";
  _uid: string;
  [k: string]: unknown;
}

export interface GridCard {
  image: StoryblokAsset;
  title: string;
  description: string;
  component: "grid_card";
  _uid: string;
  [k: string]: unknown;
}

export interface Hero {
  title: string;
  description: string;
  heading_type?: "" | "h1" | "h2";
  background_color?: "" | "black" | "green" | "red";
  image?: StoryblokAsset;
  button?: (
    | Button
    | Contact
    | CountDown
    | CountdownFeature
    | FaqItem
    | FaqSection
    | FeaturedCars
    | FeatureItem
    | Features
    | Footer
    | GridCard
    | Hero
    | HeroVideo
    | ImageGrid
    | ImageText
    | Navbar
    | NavItem
    | Page
    | Process
    | ProcessItem
    | SiteConfig
    | SocialLinkItem
  )[];
  component: "Hero";
  _uid: string;
  [k: string]: unknown;
}

export interface HeroVideo {
  title: string;
  description: string;
  heading_type?: "" | "h1" | "h2";
  background_color?: "" | "black" | "green" | "red";
  video?: StoryblokAsset;
  button?: Button[];
  poster_image?: StoryblokAsset;
  component: "HeroVideo";
  _uid: string;
  [k: string]: unknown;
}

export interface ImageGrid {
  title: string;
  text: string;
  component: "ImageGrid";
  _uid: string;
  [k: string]: unknown;
}

export interface ImageText {
  header?: string;
  title: string;
  text: string;
  button?: (
    | Button
    | Contact
    | CountDown
    | CountdownFeature
    | FaqItem
    | FaqSection
    | FeaturedCars
    | FeatureItem
    | Features
    | Footer
    | GridCard
    | Hero
    | HeroVideo
    | ImageGrid
    | ImageText
    | Navbar
    | NavItem
    | Page
    | Process
    | ProcessItem
    | SiteConfig
    | SocialLinkItem
  )[];
  image: StoryblokAsset;
  image_side: "" | "left" | "right";
  component: "ImageText";
  _uid: string;
  [k: string]: unknown;
}

export interface Navbar {
  logo?: StoryblokAsset;
  nav_links?: (
    | Button
    | Contact
    | CountDown
    | CountdownFeature
    | FaqItem
    | FaqSection
    | FeaturedCars
    | FeatureItem
    | Features
    | Footer
    | GridCard
    | Hero
    | HeroVideo
    | ImageGrid
    | ImageText
    | Navbar
    | NavItem
    | Page
    | Process
    | ProcessItem
    | SiteConfig
    | SocialLinkItem
  )[];
  component: "navbar";
  _uid: string;
  [k: string]: unknown;
}

export interface NavItem {
  link: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  label: string;
  component: "nav_item";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  title: string;
  description?: string;
  og_image?: StoryblokAsset;
  invert_menu?: boolean;
  body?: (
    | Button
    | Contact
    | CountDown
    | CountdownFeature
    | FaqItem
    | FaqSection
    | FeaturedCars
    | FeatureItem
    | Features
    | Footer
    | GridCard
    | Hero
    | HeroVideo
    | ImageGrid
    | ImageText
    | Navbar
    | NavItem
    | Page
    | Process
    | ProcessItem
    | SiteConfig
    | SocialLinkItem
  )[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Process {
  header?: string;
  title: string;
  features: (
    | Button
    | Contact
    | CountDown
    | CountdownFeature
    | FaqItem
    | FaqSection
    | FeaturedCars
    | FeatureItem
    | Features
    | Footer
    | GridCard
    | Hero
    | HeroVideo
    | ImageGrid
    | ImageText
    | Navbar
    | NavItem
    | Page
    | Process
    | ProcessItem
    | SiteConfig
    | SocialLinkItem
  )[];
  component: "Process";
  _uid: string;
  [k: string]: unknown;
}

export interface ProcessItem {
  title: string;
  text: string;
  component: "process_item";
  _uid: string;
  [k: string]: unknown;
}

export interface SiteConfig {
  site_name?: string;
  site_description?: string;
  favicon?: StoryblokAsset;
  logo?: StoryblokAsset;
  nav_links?: (
    | Button
    | Contact
    | CountDown
    | CountdownFeature
    | FaqItem
    | FaqSection
    | FeaturedCars
    | FeatureItem
    | Features
    | Footer
    | GridCard
    | Hero
    | HeroVideo
    | ImageGrid
    | ImageText
    | Navbar
    | NavItem
    | Page
    | Process
    | ProcessItem
    | SiteConfig
    | SocialLinkItem
  )[];
  cta_button?: (
    | Button
    | Contact
    | CountDown
    | CountdownFeature
    | FaqItem
    | FaqSection
    | FeaturedCars
    | FeatureItem
    | Features
    | Footer
    | GridCard
    | Hero
    | HeroVideo
    | ImageGrid
    | ImageText
    | Navbar
    | NavItem
    | Page
    | Process
    | ProcessItem
    | SiteConfig
    | SocialLinkItem
  )[];
  footer_nav_links?: (
    | Button
    | Contact
    | CountDown
    | CountdownFeature
    | FaqItem
    | FaqSection
    | FeaturedCars
    | FeatureItem
    | Features
    | Footer
    | GridCard
    | Hero
    | HeroVideo
    | ImageGrid
    | ImageText
    | Navbar
    | NavItem
    | Page
    | Process
    | ProcessItem
    | SiteConfig
    | SocialLinkItem
  )[];
  footer_logo?: StoryblokAsset;
  tagline?: string;
  social_links?: (
    | Button
    | Contact
    | CountDown
    | CountdownFeature
    | FaqItem
    | FaqSection
    | FeaturedCars
    | FeatureItem
    | Features
    | Footer
    | GridCard
    | Hero
    | HeroVideo
    | ImageGrid
    | ImageText
    | Navbar
    | NavItem
    | Page
    | Process
    | ProcessItem
    | SiteConfig
    | SocialLinkItem
  )[];
  headquarters_address?: string;
  contact_email?: string;
  contact_phone?: string;
  waitlist_text?: string;
  waitlist_button?: (
    | Button
    | Contact
    | CountDown
    | CountdownFeature
    | FaqItem
    | FaqSection
    | FeaturedCars
    | FeatureItem
    | Features
    | Footer
    | GridCard
    | Hero
    | HeroVideo
    | ImageGrid
    | ImageText
    | Navbar
    | NavItem
    | Page
    | Process
    | ProcessItem
    | SiteConfig
    | SocialLinkItem
  )[];
  copyright?: string;
  component: "site-config";
  _uid: string;
  [k: string]: unknown;
}

export interface SocialLinkItem {
  link_text: string;
  link_target: string;
  icon: StoryblokAsset;
  component: "social_link_item";
  _uid: string;
  [k: string]: unknown;
}
